CREATE DATABASE Tournament_Finder;

USE Tournament_Finder;

CREATE TABLE Users (
    USER_ID VARCHAR(10) PRIMARY KEY,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    User_tag CHAR(1), -- U for users, P for player, T for team, O for organizer
    Date_joined DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE Player (
    PLAYER_ID VARCHAR(10),
    USER_ID VARCHAR(10) DEFAULT NULL,
    age INT,
    gender VARCHAR(10) NOT NULL,
    username VARCHAR(50) NOT NULL,
    PRIMARY KEY (PLAYER_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);

CREATE TABLE Team (
    TEAM_ID VARCHAR(10),
    USER_ID VARCHAR(10), 
    PLAYER_ID VARCHAR(10),
    Team_Name VARCHAR(50),
    PRIMARY KEY (TEAM_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES Player(PLAYER_ID)
);

CREATE TABLE Team_Player (
    TEAM_ID VARCHAR(10),
    PLAYER_ID VARCHAR(10),
    PRIMARY KEY (TEAM_ID, PLAYER_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES Team(TEAM_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES Player(PLAYER_ID)
);

CREATE TABLE Organizers (
    ORGANIZER_ID VARCHAR(10),
    USER_ID VARCHAR(10),
    username VARCHAR(50) NOT NULL,
    Organization_Name VARCHAR(50) NOT NULL,
    PRIMARY KEY (ORGANIZER_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);

CREATE TABLE Tournament (
    TOURNAMENT_ID VARCHAR(10) PRIMARY KEY,
    ORGANIZER_ID VARCHAR(10),
    date DATETIME NOT NULL,
    description VARCHAR(10000) NOT NULL,
    StartEndTime VARCHAR(50) NOT NULL,
    location VARCHAR(225) NOT NULL,
    Sport_Type VARCHAR(20) NOT NULL,
    title VARCHAR(100) NOT NULL,
    poster VARCHAR(255),
    FOREIGN KEY (ORGANIZER_ID) REFERENCES Organizers(ORGANIZER_ID)
);

CREATE TABLE Tournament_Categories (
    ID VARCHAR(10) PRIMARY KEY,
    TOURNAMENT_ID VARCHAR(10),
    Category_Name VARCHAR(100),
    Fee INT,
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES Tournament(TOURNAMENT_ID)
);


CREATE TABLE Registration (
    REGISTRATION_ID VARCHAR(20) PRIMARY KEY,
    TOURNAMENT_ID VARCHAR(10),
    USER_ID VARCHAR(10),
    Registration_Date DATETIME DEFAULT CURRENT_TIMESTAMP,
    Participant_Type ENUM('player', 'team') NOT NULL,
    FOREIGN KEY (TOURNAMENT_ID) REFERENCES Tournament(TOURNAMENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES Users(USER_ID)
);

CREATE TABLE Registration_Categories (
    REGISTRATION_ID VARCHAR(20),
    CATEGORY_ID VARCHAR(10),
    PRIMARY KEY (REGISTRATION_ID, CATEGORY_ID),
    FOREIGN KEY (REGISTRATION_ID) REFERENCES Registration(REGISTRATION_ID),
    FOREIGN KEY (CATEGORY_ID) REFERENCES Tournament_Categories(ID)
);

CREATE TABLE Registration_Player (
    REGISTRATION_ID VARCHAR(20),
    PLAYER_ID VARCHAR(10),
    PRIMARY KEY (REGISTRATION_ID, PLAYER_ID),
    FOREIGN KEY (REGISTRATION_ID) REFERENCES Registration(REGISTRATION_ID),
    FOREIGN KEY (PLAYER_ID) REFERENCES Player(PLAYER_ID)
);

CREATE TABLE Registration_Team (
    REGISTRATION_ID VARCHAR(20),
    TEAM_ID VARCHAR(10),
    PRIMARY KEY (REGISTRATION_ID, TEAM_ID),
    FOREIGN KEY (REGISTRATION_ID) REFERENCES Registration(REGISTRATION_ID),
    FOREIGN KEY (TEAM_ID) REFERENCES Team(TEAM_ID)
);